# Generated by Django 2.0.8 on 2018-09-06 06:53

from django.db import migrations, models
import stdimage.models
import stdimage.utils
import stdimage.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='pictures'),
                                                        validators=[stdimage.validators.MaxSizeValidator(5000, 7000)],
                                                        verbose_name='Изображение')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
