# Generated by Django 2.2.15 on 2021-05-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='found_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.OrganizationSize', verbose_name='Размер организации'),
        ),
    ]
