# Generated by Django 2.2.15 on 2021-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210522_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='envd',
            field=models.BooleanField(default=0, verbose_name='Признак ЕНВД'),
        ),
        migrations.AddField(
            model_name='organization',
            name='eshn',
            field=models.BooleanField(default=0, verbose_name='Признак ЕСХН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='srp',
            field=models.BooleanField(default=0, verbose_name='Признак СРП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='usn',
            field=models.BooleanField(default=0, verbose_name='Признак УСН'),
        ),
    ]
