# Generated by Django 2.2.15 on 2021-05-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationcorrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_coefficient', models.FloatField(default=3.5, verbose_name='Пороговое значения коэффициента похожести организаций')),
            ],
            options={
                'verbose_name': 'Коэффициенты',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.AlterModelOptions(
            name='supportmeasures',
            options={'verbose_name': 'Мера поддержки', 'verbose_name_plural': 'Меры поддержки'},
        ),
    ]
