# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_federalsubject_federal_subject_type_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federalsubject',
            options={'ordering': ['name'], 'verbose_name': 'Федеральный субъект', 'verbose_name_plural': 'Федеральные субъекты'},
        ),
    ]
