# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 08:15
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    omit_city(apps, schema_editor, forward=True)


def reverse_func(apps, schema_editor):
    omit_city(apps, schema_editor, forward=False)


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20170912_1622'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]


def omit_city(apps, schema_editor, forward=True):
    FederalSubject = apps.get_model("regions", "FederalSubject")

    FederalSubject.objects.filter(federal_subject_type__full_name='Город')\
        .update(federal_subject_type_position=['prefix', 'omit'][forward])
