# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_omit_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalsubject',
            name='timezones',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Часовые пояса'),
        ),
    ]
