# Generated by Django 2.0.7 on 2018-10-18 12:30

from django.db import migrations, models


def forward_func(apps, schema_editor):
    FederalSubject = apps.get_model("regions", "FederalSubject")
    FederalSubject.objects.filter(id=12).update(deleted=True)


def reverse_func(apps, schema_editor):
    FederalSubject = apps.get_model("regions", "FederalSubject")
    FederalSubject.objects.filter(id=12).update(deleted=False)


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_change_arkhangelsk_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalsubject',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленно'),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
