# Generated by Django 2.0.7 on 2019-01-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_federalsubject_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='federalsubject',
            index=models.Index(fields=['name'], name='regions_fed_name_48125e1_idx'),
        ),
    ]
