# Generated by Django 2.0.7 on 2019-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_rename_kuzbass'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalsubject',
            name='system_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Полное название'),
        ),
    ]
